# Generated by Django 4.1.2 on 2022-12-03 05:28

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('teamhyena2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_policy_contacts',
            name='company_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
